name = "impa-pdf-search"
compatibility_date = "2024-10-03"

# 构建配置
[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

# Pages 配置
pages_build_output_dir = "out"

# 环境变量
[env.production.vars]
NODE_VERSION = "18"
NPM_VERSION = "9"
